version: '3'

services:
#  webserver:
#    build: java/
#    ports:
#      - "8085:8085"
#      - "443:443"
#    links:
#      - mysql

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
